app = "cute"
primary_region = 'sin'

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
image = "wordpress:latest"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
http_checks = []
internal_port = 80
processes = ["app"]
protocol = "tcp"
script_checks = []

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"

[mounts]
source = "wordpress"
destination = "/bitnami/wordpress"
initial_size = '500GB'

[[vm]]
  memory = '128gb'
  cpu_kind = 'performance'
  cpus = 16
